all_output: "ips-all.txt"   # 全量汇总（不受 count 限制）
output:
  "main.txt":
    routes:
      - name: "qms_ct"
        enable: true
        type: dns
        domain: "ct.877774.xyz"
        dns:
          - "https://dns.google/dns-query&ecs=14.153.0.0/24"
          - "https://cloudflare-dns.com/dns-query&ecs=14.153.0.0/24"
          - "1.1.1.1&ecs=14.152.0.0/24"
          - "8.8.8.8&ecs=14.152.0.0/24"
          - "223.5.5.5&ecs=14.145.0.0/24"
          - "119.29.29.29&ecs=14.145.0.0/24"
        count: 2
        additional-prefix: "🗺️ qms电信-"
        additional-suffix: "|负载均衡"
        fallback: "172.64.229.44#⚠️ 后备|负载均衡"

      - name: "qms_na"
        enable: true
        type: dns
        domain: "na.877774.xyz"
        dns:
          - "https://dns.google/dns-query&ecs=14.153.0.0/24"
          - "https://cloudflare-dns.com/dns-query&ecs=14.153.0.0/24"
          - "1.1.1.1&ecs=14.152.0.0/24"
          - "8.8.8.8&ecs=14.152.0.0/24"
          - "223.5.5.5&ecs=14.145.0.0/24"
          - "119.29.29.29&ecs=14.145.0.0/24"
        count: 2
        additional-prefix: "🤠 qms美洲-"
        additional-suffix: "|自动选择"
        fallback: "104.19.74.233#⚠️ 后备|自动选择"

  "test-a.txt":
    routes:
      - name: "微测优选"
        enable: true
        type: http
        url: "https://bestcf.pages.dev/wetest/ipv4.txt"
        filter: "(?i)^(?=.*(lax|us|美国))(?!.*(bestcf|ipv6)).*$"
        count: 4
        additional-prefix: "🍩 微测-us-"
        additional-suffix: "|test-a"
        fallback: "104.17.110.199#⚠️ 后备|test-a"

  "test-b.txt":
    routes:
      - name: "Senflare"
        enable: true
        type: http
        url: "https://raw.githubusercontent.com/Senflare/Senflare-IP/refs/heads/main/Senflare-Pro.txt"
        filter: "(?i)^(?=.*(lax|us|美国))(?!.*(bestcf|ipv6)).*$"
        count: 4
        additional-prefix: "🌵 Senflare-us-"
        additional-suffix: "|test-b"
        fallback: "104.16.103.103#⚠️ 后备|test-b"
